# Generated by Django 6.0.4 on 2026-05-15 20:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buy_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saved_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-saved_date', 'name'],
            },
        ),
    ]
